### ISSUE TITLE
Pasting content with multiple lines into Microsoft Terminal (uwp)

### ISSUE THREAD

**Issue by dudeisbrendan03** [benweissmann/getmic.ro#24]
When pasting content into mic.ro in Microsoft terminal it will add an extra indent for each line pasted.

e.g.

Original content:
```js
if (a===b) {
	doC();
} else {
	doD(false);
}
```

Pasted content:
```js
if (a===b) {
		doC();
		} else {
				doD(false);
				}
```

**Comment by zyedidia** [comment]
It seems like this is an issue with https://github.com/zyedidia/micro, not this repository (which is just a script to download micro). You should open an issue there if you want to continue the discussion. The reason this happens is because you need to set the `paste` option to `on`, or use `Ctrl-v` instead of your terminal keybinding to perform the paste. When you use your terminal keybinding to paste, the terminal just sends all the characters to micro as if you typed them one by one. Enabling the `paste` option lets micro know that the characters being sent by the terminal are part of a paste event and should be grouped together and autoindent/autoclose shouldn't be applied.

**Comment by dudeisbrendan03** [comment]
> It seems like this is an issue with https://github.com/zyedidia/micro, not this repository (which is just a script to download micro). You should open an issue there if you want to continue the discussion. The reason this happens is because you need to set the `paste` option to `on`, or use `Ctrl-v` instead of your terminal keybinding to perform the paste. When you use your terminal keybinding to paste, the terminal just sends all the characters to micro as if you typed them one by one. Enabling the `paste` option lets micro know that the characters being sent by the terminal are part of a paste event and should be grouped together and autoindent/autoclose shouldn't be applied.

I realised yesterday! My bad, I'll head over there now :)

I am using my binding set in Microsoft Terminal (ctrl+shift+v) and not the clipboard management in micro
