### ISSUE TITLE
Install fails with  INSUFFICIENT PRIVILEGES

### ISSUE THREAD

**Issue by mrx23dot** [benweissmann/getmic.ro#33]
Install fails with  INSUFFICIENT PRIVILEGES

details:
https://github.com/zyedidia/micro/issues/2349

**Comment by fgardt** [comment]
You need to run `curl https://getmic.ro | sudo sh`. The downloading doesn't require elevated privileges where as the script execution does.

**Comment by anonyco** [comment]
> You need to run `curl https://getmic.ro | sudo sh`. The downloading doesn't require elevated privileges where as the script execution does.

By the way, this solution was actually mentioned in the error message.  I'll add a fix to my PR so that we won't get more issues.

**Comment by benweissmann** [comment]
@mrx23dot I'm going to close this issue since it looks like other folks have provided some help; there's ongoing discussion in https://github.com/benweissmann/getmic.ro/pull/32 of how we can improve the UX around this feature for non-root users.

Let's keep discussion around getmic.ro on this repo rather than https://github.com/zyedidia/micro to avoid bothering the maintainers over there -- if we decide that it's important to update official docs in that repo, we can make that request, but we shouldn't do that before we discuss here first and consider ways of improving getmic.ro without needing to make changes to already-documented install procedures.
